version: '3.1'

services:

  db:
    image: mysql:5.7
    container_name: todo-list-db
    restart: always
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

  back-end:
    build: ./back-end
    image: todo-list-back-end
    container_name: todo-list-back-end
    user: node
    depends_on:
      - db
    restart: always
    env_file:
      - ./.env
    environment:
      SERVER_PORT: ${SERVER_PORT}
      JWT_SECRET: ${JWT_SECRET}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_HOST: db
    # ports:
    #   - 3010:${SERVER_PORT}
    volumes:
      - ./back-end:/app
    command: npm run dev

  front-end:
    build: ./front-end
    image: todo-list-front-end
    container_name: todo-list-front-end
    depends_on:
      - back-end
    restart: always
    env_file:
      - ./.env
    environment:
      REACT_APP_BACKEND_HOST: back-end
      REACT_APP_BACKEND_PORT: ${SERVER_PORT}
    ports:
      - 3000:3000
    volumes:
      - ./front-end:/app
    command: npm start
